import { Archive, File, FileText, Package } from "lucide-react";
import type { EntryVisual, FileVisualGroup } from "./fileVisualTypes";

export const FILE_VISUALS: Record<
  FileVisualGroup,
  EntryVisual
> = {
  "file-document": {
    group: "file-document",
    slot: "tc-file-text",
    icon: FileText,
    iconSize: 12,
    iconClassName: "theme-tc-file-glyph theme-tc-file-glyph-text",
    iconWrapperClassName: "theme-tc-icon-slot theme-tc-slot-text-file theme-tc-type-document",
    nameClassName: "theme-tc-file-name",
    nameWeightClassName: "font-medium",
  },
  "file-pdf": {
    group: "file-pdf",
    slot: "tc-file-associated",
    icon: File,
    iconSize: 12,
    iconClassName: "theme-tc-file-glyph theme-tc-file-glyph-associated",
    iconWrapperClassName: "theme-tc-icon-slot theme-tc-slot-associated-file theme-tc-type-document",
    nameClassName: "theme-tc-file-name",
    nameWeightClassName: "font-medium",
  },
  "file-spreadsheet": {
    group: "file-spreadsheet",
    slot: "tc-file-associated",
    icon: File,
    iconSize: 12,
    iconClassName: "theme-tc-file-glyph theme-tc-file-glyph-associated",
    iconWrapperClassName: "theme-tc-icon-slot theme-tc-slot-associated-file theme-tc-type-spreadsheet",
    nameClassName: "theme-tc-file-name",
    nameWeightClassName: "font-medium",
  },
  "file-presentation": {
    group: "file-presentation",
    slot: "tc-file-associated",
    icon: File,
    iconSize: 12,
    iconClassName: "theme-tc-file-glyph theme-tc-file-glyph-associated",
    iconWrapperClassName: "theme-tc-icon-slot theme-tc-slot-associated-file theme-tc-type-presentation",
    nameClassName: "theme-tc-file-name",
    nameWeightClassName: "font-medium",
  },
  "file-data": {
    group: "file-data",
    slot: "tc-file-associated",
    icon: File,
    iconSize: 12,
    iconClassName: "theme-tc-file-glyph theme-tc-file-glyph-associated",
    iconWrapperClassName: "theme-tc-icon-slot theme-tc-slot-associated-file theme-tc-type-data",
    nameClassName: "theme-tc-file-name",
    nameWeightClassName: "font-medium",
  },
  "file-image": {
    group: "file-image",
    slot: "tc-file-associated",
    icon: File,
    iconSize: 12,
    iconClassName: "theme-tc-file-glyph theme-tc-file-glyph-associated",
    iconWrapperClassName: "theme-tc-icon-slot theme-tc-slot-associated-file theme-tc-type-image",
    nameClassName: "theme-tc-file-name",
    nameWeightClassName: "font-medium",
  },
  "file-archive": {
    group: "file-archive",
    slot: "tc-file-archive",
    icon: Archive,
    iconSize: 12,
    iconClassName: "theme-tc-file-glyph theme-tc-file-glyph-archive",
    iconWrapperClassName: "theme-tc-icon-slot theme-tc-slot-archive-file",
    nameClassName: "theme-tc-file-name",
    nameWeightClassName: "font-medium",
  },
  "file-code": {
    group: "file-code",
    slot: "tc-file-text",
    icon: FileText,
    iconSize: 12,
    iconClassName: "theme-tc-file-glyph theme-tc-file-glyph-text",
    iconWrapperClassName: "theme-tc-icon-slot theme-tc-slot-text-file theme-tc-type-code",
    nameClassName: "theme-tc-file-name",
    nameWeightClassName: "font-medium",
  },
  "file-config": {
    group: "file-config",
    slot: "tc-file-text",
    icon: FileText,
    iconSize: 12,
    iconClassName: "theme-tc-file-glyph theme-tc-file-glyph-text",
    iconWrapperClassName: "theme-tc-icon-slot theme-tc-slot-text-file theme-tc-type-config",
    nameClassName: "theme-tc-file-name",
    nameWeightClassName: "font-medium",
  },
  "file-audio": {
    group: "file-audio",
    slot: "tc-file-associated",
    icon: File,
    iconSize: 12,
    iconClassName: "theme-tc-file-glyph theme-tc-file-glyph-associated",
    iconWrapperClassName: "theme-tc-icon-slot theme-tc-slot-associated-file theme-tc-type-media",
    nameClassName: "theme-tc-file-name",
    nameWeightClassName: "font-medium",
  },
  "file-video": {
    group: "file-video",
    slot: "tc-file-associated",
    icon: File,
    iconSize: 12,
    iconClassName: "theme-tc-file-glyph theme-tc-file-glyph-associated",
    iconWrapperClassName: "theme-tc-icon-slot theme-tc-slot-associated-file theme-tc-type-media",
    nameClassName: "theme-tc-file-name",
    nameWeightClassName: "font-medium",
  },
  "file-installer": {
    group: "file-installer",
    slot: "tc-file-program",
    icon: Package,
    iconSize: 12,
    iconClassName: "theme-tc-file-glyph theme-tc-file-glyph-program",
    iconWrapperClassName: "theme-tc-icon-slot theme-tc-slot-program-file",
    nameClassName: "theme-tc-file-name",
    nameWeightClassName: "font-semibold",
  },
  "file-app": {
    group: "file-app",
    slot: "tc-file-program",
    icon: Package,
    iconSize: 12,
    iconClassName: "theme-tc-file-glyph theme-tc-file-glyph-program",
    iconWrapperClassName: "theme-tc-icon-slot theme-tc-slot-program-file",
    nameClassName: "theme-tc-file-name",
    nameWeightClassName: "font-medium",
  },
  "file-default": {
    group: "file-default",
    slot: "tc-file-standard",
    icon: File,
    iconSize: 12,
    iconClassName: "theme-tc-file-glyph theme-tc-file-glyph-standard",
    iconWrapperClassName: "theme-tc-icon-slot theme-tc-slot-standard-file",
    nameClassName: "theme-tc-file-name",
    nameWeightClassName: "",
  },
};

export const HIDDEN_FILE_VISUAL: EntryVisual = {
  group: "file-hidden",
  slot: "tc-file-hidden",
  icon: File,
  iconSize: 12,
  iconClassName: "theme-tc-file-glyph theme-tc-file-glyph-hidden",
  iconWrapperClassName: "theme-tc-icon-slot theme-tc-slot-standard-file theme-tc-slot-hidden-file",
  nameClassName: "theme-tc-hidden-name",
  nameWeightClassName: "font-medium",
  overlayClassName: "theme-tc-overlay-hidden",
};
