export const DOCUMENT_EXTENSIONS = new Set([
  "txt",
  "md",
  "markdown",
  "doc",
  "docx",
  "rtf",
  "odt",
  "pages",
]);
export const PDF_EXTENSIONS = new Set(["pdf"]);
export const SPREADSHEET_EXTENSIONS = new Set(["xls", "xlsx", "ods", "numbers"]);
export const PRESENTATION_EXTENSIONS = new Set(["ppt", "pptx", "odp", "key"]);
export const DATA_EXTENSIONS = new Set(["csv", "tsv", "parquet", "sqlite", "sqlite3", "db"]);
export const IMAGE_EXTENSIONS = new Set([
  "png",
  "jpg",
  "jpeg",
  "gif",
  "webp",
  "svg",
  "bmp",
  "ico",
  "heic",
  "avif",
]);
export const ARCHIVE_EXTENSIONS = new Set([
  "zip",
  "rar",
  "7z",
  "tar",
  "gz",
  "bz2",
  "xz",
  "tgz",
]);
export const CODE_EXTENSIONS = new Set([
  "ts",
  "tsx",
  "js",
  "jsx",
  "mjs",
  "cjs",
  "json",
  "jsonc",
  "rs",
  "py",
  "java",
  "kt",
  "go",
  "rb",
  "php",
  "swift",
  "c",
  "cc",
  "cpp",
  "h",
  "hpp",
  "cs",
  "html",
  "css",
  "scss",
  "sass",
  "sql",
  "sh",
  "zsh",
  "bash",
]);
export const CONFIG_EXTENSIONS = new Set([
  "env",
  "gitignore",
  "editorconfig",
  "ini",
  "cfg",
  "conf",
  "yaml",
  "yml",
  "toml",
  "lock",
]);
export const AUDIO_EXTENSIONS = new Set(["mp3", "wav", "flac", "aac", "ogg", "m4a"]);
export const VIDEO_EXTENSIONS = new Set(["mp4", "mkv", "mov", "avi", "webm", "wmv", "m4v"]);
export const APP_BUNDLE_EXTENSIONS = new Set(["app"]);
export const INSTALLER_EXTENSIONS = new Set(["dmg", "pkg", "exe", "msi", "deb", "rpm", "apk", "appimage"]);
export const DOCUMENT_FILENAMES = new Set(["readme", "license", "changelog"]);
export const ARCHIVE_SUFFIXES = [".tar.gz", ".tar.bz2", ".tar.xz"];

export const EXTENSION_LABEL_OVERRIDES: Record<string, string> = {
  markdown: "MD",
  docx: "DOC",
  pages: "DOC",
  xlsx: "XLS",
  ods: "XLS",
  numbers: "XLS",
  pptx: "PPT",
  odp: "PPT",
  key: "PPT",
  sqlite: "DB",
  sqlite3: "DB",
  jpeg: "JPG",
  tiff: "TIF",
  appimage: "APP",
  json: "JSN",
  jsonc: "JSC",
  jsx: "JSX",
  mjs: "JS",
  cjs: "JS",
  tsx: "TSX",
  html: "HTM",
  scss: "SCS",
  sass: "SAS",
  bash: "SH",
  zsh: "SH",
  yaml: "YML",
  yml: "YML",
  gitignore: "GIT",
  editorconfig: "ED",
  lock: "LCK",
};

export const FILENAME_LABEL_OVERRIDES: Record<string, string> = {
  readme: "TXT",
  license: "TXT",
  changelog: "LOG",
};

export const EXTENSION_LABEL_CLASS_OVERRIDES: Record<string, string> = {
  txt: "theme-tc-ext-txt",
  md: "theme-tc-ext-md",
  markdown: "theme-tc-ext-md",
  doc: "theme-tc-ext-doc",
  docx: "theme-tc-ext-doc",
  odt: "theme-tc-ext-doc",
  pages: "theme-tc-ext-doc",
  rtf: "theme-tc-ext-doc",
  pdf: "theme-tc-ext-pdf",
  xls: "theme-tc-ext-xls",
  xlsx: "theme-tc-ext-xls",
  ods: "theme-tc-ext-xls",
  numbers: "theme-tc-ext-xls",
  ppt: "theme-tc-ext-ppt",
  pptx: "theme-tc-ext-ppt",
  odp: "theme-tc-ext-ppt",
  key: "theme-tc-ext-ppt",
  csv: "theme-tc-ext-csv",
  tsv: "theme-tc-ext-csv",
  sqlite: "theme-tc-ext-db",
  sqlite3: "theme-tc-ext-db",
  db: "theme-tc-ext-db",
  jpg: "theme-tc-ext-jpg",
  jpeg: "theme-tc-ext-jpg",
  png: "theme-tc-ext-png",
  gif: "theme-tc-ext-gif",
  svg: "theme-tc-ext-svg",
  webp: "theme-tc-ext-webp",
  bmp: "theme-tc-ext-image",
  ico: "theme-tc-ext-image",
  heic: "theme-tc-ext-image",
  avif: "theme-tc-ext-image",
  tif: "theme-tc-ext-image",
  tiff: "theme-tc-ext-image",
  zip: "theme-tc-ext-zip",
  rar: "theme-tc-ext-rar",
  "7z": "theme-tc-ext-7z",
  tar: "theme-tc-ext-tar",
  gz: "theme-tc-ext-tar",
  bz2: "theme-tc-ext-tar",
  xz: "theme-tc-ext-tar",
  tgz: "theme-tc-ext-tar",
  ts: "theme-tc-ext-ts",
  tsx: "theme-tc-ext-ts",
  js: "theme-tc-ext-js",
  jsx: "theme-tc-ext-js",
  mjs: "theme-tc-ext-js",
  cjs: "theme-tc-ext-js",
  json: "theme-tc-ext-json",
  jsonc: "theme-tc-ext-json",
  py: "theme-tc-ext-py",
  rs: "theme-tc-ext-rs",
  go: "theme-tc-ext-go",
  java: "theme-tc-ext-java",
  kt: "theme-tc-ext-java",
  rb: "theme-tc-ext-rb",
  php: "theme-tc-ext-php",
  swift: "theme-tc-ext-swift",
  c: "theme-tc-ext-c",
  cc: "theme-tc-ext-c",
  cpp: "theme-tc-ext-c",
  h: "theme-tc-ext-c",
  hpp: "theme-tc-ext-c",
  cs: "theme-tc-ext-cs",
  html: "theme-tc-ext-html",
  css: "theme-tc-ext-css",
  scss: "theme-tc-ext-css",
  sass: "theme-tc-ext-css",
  sql: "theme-tc-ext-sql",
  sh: "theme-tc-ext-shell",
  zsh: "theme-tc-ext-shell",
  bash: "theme-tc-ext-shell",
  env: "theme-tc-ext-env",
  gitignore: "theme-tc-ext-config",
  editorconfig: "theme-tc-ext-config",
  ini: "theme-tc-ext-config",
  cfg: "theme-tc-ext-config",
  conf: "theme-tc-ext-config",
  yaml: "theme-tc-ext-yaml",
  yml: "theme-tc-ext-yaml",
  toml: "theme-tc-ext-toml",
  lock: "theme-tc-ext-lock",
  mp3: "theme-tc-ext-mp3",
  wav: "theme-tc-ext-audio",
  flac: "theme-tc-ext-audio",
  aac: "theme-tc-ext-audio",
  ogg: "theme-tc-ext-audio",
  m4a: "theme-tc-ext-audio",
  mp4: "theme-tc-ext-mp4",
  mkv: "theme-tc-ext-video",
  mov: "theme-tc-ext-video",
  avi: "theme-tc-ext-video",
  webm: "theme-tc-ext-video",
  wmv: "theme-tc-ext-video",
  m4v: "theme-tc-ext-video",
  dmg: "theme-tc-ext-mac",
  pkg: "theme-tc-ext-mac",
  exe: "theme-tc-ext-win",
  msi: "theme-tc-ext-win",
  deb: "theme-tc-ext-linux",
  rpm: "theme-tc-ext-linux",
  apk: "theme-tc-ext-linux",
  appimage: "theme-tc-ext-linux",
  app: "theme-tc-ext-app",
  bin: "theme-tc-ext-bin",
};

export const FILENAME_LABEL_CLASS_OVERRIDES: Record<string, string> = {
  readme: "theme-tc-ext-md",
  license: "theme-tc-ext-txt",
  changelog: "theme-tc-ext-txt",
};

export const ARCHIVE_LABEL_SUFFIXES: Array<[suffix: string, label: string]> = [
  [".tar.gz", "TGZ"],
  [".tar.bz2", "TBZ"],
  [".tar.xz", "TXZ"],
];

export const ARCHIVE_LABEL_SUFFIX_CLASSES: Array<[suffix: string, className: string]> = [
  [".tar.gz", "theme-tc-ext-tar"],
  [".tar.bz2", "theme-tc-ext-tar"],
  [".tar.xz", "theme-tc-ext-tar"],
];
