#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"
target_file="${repo_root}/.claudeignore"

cat > "${target_file}" <<'EOF'
# Generated by scripts/generate-claudeignore.sh
# Keep source, docs, tracked config, and lockfiles readable.

# Dependencies
node_modules/

# Build / test outputs
dist/
dist-ssr/
coverage/
src-tauri/target/
mindvault-out/
.vitest-localstorage
.vitest-localstorage-shm
.vitest-localstorage-wal
*.tsbuildinfo

# Logs / transient diagnostics
logs/
*.log
build_log.txt
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Secrets / machine-local config
.env
.env.*
*.local

# Local tool state and duplicated worktrees
.omc/
.omx/logs/
.omx/state/
.omx/metrics.json
.omx/notepad.md
.claude/worktrees/
.claude/settings.local.json

# Editor / OS / VCS internals
.vscode/
.idea/
.DS_Store
Thumbs.db
.git/
EOF

printf 'Wrote %s\n' "${target_file}"
